version: '3.7'

services:
  prometheus:
    image: "941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/monitoring:prometheus"
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - monitoring

  grafana:
    image: "941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/monitoring:grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - monitoring

  node-exporter:
    image: "941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/monitoring:node-exporter"
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring

  loki:
    image: "941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/monitoring:loki"
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: "941377153895.dkr.ecr.ap-northeast-2.amazonaws.com/oops/monitoring:promtail"
    container_name: promtail
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log  # 호스트 로그 디렉토리를 컨테이너에 마운트
    command: -config.file=/etc/promtail/promtail-config.yml
    ports:
      - "9080:9080"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge