server:
  http_listen_port: 9080  # Promtail의 API 서버 포트

positions:
  filename: /tmp/positions.yaml  # 로그 수집 위치 저장 파일

clients:
  - url: "http://loki:3100/loki/api/v1/push"  # Loki로 로그 전송

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log  # 수집할 로그 경로
